"""nexa-bidkit: day-ahead and intraday auction bid generation for European power markets."""

from nexa_bidkit.bids import (
    BlockBid,
    ExclusiveGroupBid,
    LinkedBlockBid,
    SimpleBid,
    block_bid,
    exclusive_group,
    generate_bid_id,
    indivisible_block_bid,
    linked_block_bid,
    simple_bid_from_curve,
    validate_bid_collection,
    with_status,
)
from nexa_bidkit.curves import (
    aggregate_by_price,
    clip_curve,
    constant_curve,
    empty_curve,
    filter_zero_volume,
    from_dataframe,
    from_dict_list,
    from_series_pair,
    get_curve_summary,
    linear_curve,
    merge_curves,
    scale_curve,
    validate_dataframe_schema,
)
from nexa_bidkit.curves import to_dataframe as curves_to_dataframe
from nexa_bidkit.orders import (
    OrderBook,
    add_bid,
    add_bids,
    count_bids,
    create_order_book,
    filter_bids,
    get_bid_by_id,
    get_bids_by_direction,
    get_bids_by_status,
    get_bids_by_type,
    get_bids_by_zone,
    get_bids_in_period,
    get_order_book_summary,
    remove_bid,
    total_volume_by_zone,
    update_all_statuses,
    update_bid_status,
)
from nexa_bidkit.orders import to_dataframe as orders_to_dataframe
from nexa_bidkit.types import (
    BiddingZone,
    BidStatus,
    BidType,
    CurveType,
    DeliveryPeriod,
    Direction,
    MTUDuration,
    MTUInterval,
    Price,
    PriceQuantityCurve,
    PriceQuantityStep,
    Volume,
)
from nexa_bidkit.validation import (
    DataQualityError,
    EuphemiaValidationError,
    PortfolioValidationError,
    TemporalValidationError,
    ValidationError,
    get_validation_summary,
    validate_bid,
    validate_bids,
    validate_block_bid,
    validate_exclusive_group_bid,
    validate_gate_closure,
    validate_linked_block_bid,
    validate_order_book_bids,
    validate_order_book_for_submission,
    validate_price_quantity_curve,
    validate_simple_bid,
)

__all__ = [
    # Bid models
    "SimpleBid",
    "BlockBid",
    "LinkedBlockBid",
    "ExclusiveGroupBid",
    # Bid construction helpers
    "generate_bid_id",
    "simple_bid_from_curve",
    "block_bid",
    "indivisible_block_bid",
    "linked_block_bid",
    "exclusive_group",
    "with_status",
    "validate_bid_collection",
    # OrderBook models and functions
    "OrderBook",
    "create_order_book",
    "add_bid",
    "add_bids",
    "remove_bid",
    "filter_bids",
    "get_bid_by_id",
    "get_bids_by_zone",
    "get_bids_by_direction",
    "get_bids_by_status",
    "get_bids_by_type",
    "get_bids_in_period",
    "count_bids",
    "total_volume_by_zone",
    "get_order_book_summary",
    "update_bid_status",
    "update_all_statuses",
    "orders_to_dataframe",
    # Curve construction and manipulation
    "aggregate_by_price",
    "clip_curve",
    "constant_curve",
    "empty_curve",
    "filter_zero_volume",
    "from_dataframe",
    "from_dict_list",
    "from_series_pair",
    "get_curve_summary",
    "linear_curve",
    "merge_curves",
    "scale_curve",
    "curves_to_dataframe",
    "validate_dataframe_schema",
    # Validation exceptions
    "ValidationError",
    "EuphemiaValidationError",
    "DataQualityError",
    "TemporalValidationError",
    "PortfolioValidationError",
    # Validation functions
    "validate_bid",
    "validate_bids",
    "validate_simple_bid",
    "validate_block_bid",
    "validate_linked_block_bid",
    "validate_exclusive_group_bid",
    "validate_price_quantity_curve",
    "validate_order_book_bids",
    "validate_order_book_for_submission",
    "validate_gate_closure",
    "get_validation_summary",
    # Types
    "BiddingZone",
    "BidStatus",
    "BidType",
    "CurveType",
    "DeliveryPeriod",
    "Direction",
    "MTUDuration",
    "MTUInterval",
    "Price",
    "PriceQuantityCurve",
    "PriceQuantityStep",
    "Volume",
]
